### ISSUE TITLE
API Changes

### ISSUE THREAD

**Issue by madebyspark** [brandonohara/SimplEE-Instagram#2]
Hey there,

WIll this plugin work with the new Instagram API changes that went into effect today?

Thanks,
Danielle

**Comment by brandonohara** [comment]
As of right now no, I've stopped working with ExpressionEngine at my new job and don't foresee having time to fix this in the near future. If you have an approved API Key however, I can't imagine it wouldn't work.

**Comment by madebyspark** [comment]
Thanks - I have a valid key but it fails anyway. Appreciate the reply.
