### ISSUE TITLE
access token

### ISSUE THREAD

**Issue by kdesigns** [brandonohara/SimplEE-Instagram#3]
I would like to use this add-on, however, Instagram required an access token to request the feeds.
Currently I'm using Pic Puller for Instagram on EE2 but I want to upgrade to EE3. Your add-on works on EE3 but not since you need an access token.
Will you be updating?

**Comment by brandonohara** [comment]
Hey kdesigns, I will not have a chance to update this plugin. I've stopped working with ExpressionEngine so I won't have time to update things to Instagram's latest restrictions.
