### ISSUE TITLE
Updating readme ?

### ISSUE THREAD

**Issue by LouWii** [brandonohara/SimplEE-Instagram#4]
Hi there,

It would be nice to actually put in the readme that this add-on doesn't work anymore due to API changes.
Or at least leave an issue open so people can see it.

I've wasted my time here. It's always the same with dead Github projects...

**Comment by brandonohara** [comment]
It must have been such an inconvenience for you to use free software I thought I'd share with the community, and haven't had time to update. 

I will update the readme, no need to be an asshole.
